<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Style-Type" content="text/css" />

    <title>Политика обработки персональных данных</title>
    <style type="text/css">.awlist1 { list-style-type:none; counter-reset:awlistcounter1 }.awlist1 li:before { content:"1."counter(awlistcounter1)"."; counter-increment:awlistcounter1 }.awlist2 { list-style-type:none; counter-reset:awlistcounter2 }.awlist2 li:before { content:"1.2."counter(awlistcounter2)"."; counter-increment:awlistcounter2 }.awlist3 { list-style-type:none; counter-reset:awlistcounter3 }.awlist3 li:before { content:"2."counter(awlistcounter3)"."; counter-increment:awlistcounter3 }.awlist4 { list-style-type:none; counter-reset:awlistcounter4 }.awlist4 li:before { content:"3."counter(awlistcounter4)"."; counter-increment:awlistcounter4 }.awlist5 { list-style-type:none; counter-reset:awlistcounter5 }.awlist5 li:before { content:"3.1."counter(awlistcounter5)"."; counter-increment:awlistcounter5 }.awlist6 { list-style-type:none; counter-reset:awlistcounter6 }.awlist6 li:before { content:"4."counter(awlistcounter6)"."; counter-increment:awlistcounter6 }.awlist7 { list-style-type:none; counter-reset:awlistcounter7 }.awlist7 li:before { content:"4.1."counter(awlistcounter7)"."; counter-increment:awlistcounter7 }.awlist8 { list-style-type:none; counter-reset:awlistcounter8 }.awlist8 li:before { content:"4.3."counter(awlistcounter8)"."; counter-increment:awlistcounter8 }.awlist9 { list-style-type:none; counter-reset:awlistcounter9 }.awlist9 li:before { content:"5."counter(awlistcounter9)"."; counter-increment:awlistcounter9 }.awlist10 { list-style-type:none; counter-reset:awlistcounter10 }.awlist10 li:before { content:"6."counter(awlistcounter10)"."; counter-increment:awlistcounter10 }.awlist11 { list-style-type:none; counter-reset:awlistcounter11 }.awlist11 li:before { content:"6.2."counter(awlistcounter11)"."; counter-increment:awlistcounter11 }</style>

    <style>
        body {
            padding-right: 25px;
        }
    </style>
</head>
<body>
<div>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:108%; font-size:11pt"><a name="h.gjdgxs"></a><span style="font-family:Calibri; font-weight:bold">Политика</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">обработки</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">персональных</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">данных</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">и</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">обеспечения</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">безопасности</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">при</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">их</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">обработке</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">через</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">сайт</span><span style="font-family:Calibri; font-weight:bold"> </span><span style="font-family:Calibri; font-weight:bold">Podpishi</span><span style="font-family:Calibri; font-weight:bold">.</span><span style="font-family:Calibri; font-weight:bold">org</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:108%; font-size:11pt"><span style="font-family:Calibri">&#xa0;</span></p>
    <ol type="1" style="margin:0pt; padding-left:0pt">
        <li style="margin-left:31.51pt; line-height:108%; padding-left:4.49pt; font-family:Calibri; font-size:11pt; font-weight:bold">
            <span>Общие</span><span> </span><span>положения</span><span> </span><span>и</span><span> </span><span>определения</span>
            <ol type="1" class="awlist1" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                <li style="text-indent:-18pt; text-align:justify; font-weight:normal; list-style-position:inside"><span>Настоящая</span><span> </span><span>Политика</span><span> </span><span>обработки</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>и</span><span> </span><span>обеспечения</span><span> </span><span>безопасности</span><span> </span><span>при</span><span> </span><span>их</span><span> </span><span>обработке</span><span> (</span><span>далее</span><span> – </span><span>Политика</span><span>) </span><span>принята</span><span> </span><span>владельцем</span><span> </span><span>сайта</span><span> </span><span>https</span><span>://</span><span>podpishi</span><span>.</span><span>org</span><span> </span><span>Максимом</span><span> </span><span>Евгеньевичем</span><span> </span><span>Кацем</span><span> </span><span>в</span><span> </span><span>целях</span><span> </span><span>регламентации</span><span> </span><span>основных</span><span> </span><span>вопросов</span><span> </span><span>обработки</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>субъектов</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>, </span><span>обеспечения</span><span> </span><span>конфиденциальности</span><span> </span><span>и</span><span> </span><span>защиты</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>от</span><span> </span><span>несанкционированного</span><span> </span><span>доступа</span><span>, </span><span>неправомерного</span><span> </span><span>их</span><span> </span><span>использования</span><span>, </span><span>разглашения</span><span> </span><span>или</span><span> </span><span>утраты</span><span> </span><span>при</span><span> </span><span>использовании</span><span> </span><span>данного</span><span> </span><span>сайта</span><span> </span><span>в</span><span> </span><span>целях</span><span> </span><span>формирования</span><span> </span><span>обращений</span><span> </span><span>для</span><span> </span><span>подачи</span><span> </span><span>в</span><span> </span><span>органы</span><span> </span><span>государственной</span><span> </span><span>власти</span><span>, </span><span>местного</span><span> </span><span>самоуправления</span><span>, </span><span>должностным</span><span> </span><span>лицам</span><span>. </span></li>
                <li style="text-indent:-18pt; text-align:justify; font-weight:normal; list-style-position:inside">
                    <span>Основные</span><span> </span><span>понятия</span><span>, </span><span>используемые</span><span> </span><span>в</span><span> </span><span>Политике</span><span>:</span><a name="id.30j0zll"></a>
                    <ol type="1" class="awlist2" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>Оператор</span><span> – </span><span>Максим</span><span> </span><span>Евгеньевич</span><span> </span><span>Кац</span><span>, 23.12.1984 </span><span>г</span><span>. </span><span>рождения</span><span>, </span><span>являющийся</span><span> </span><span>владельцем</span><span> </span><span>сайта</span><span> </span><span>https</span><span>://</span><span>podpishi</span><span>.</span><span>org</span><span> </span><span>и</span><span> </span><span>оператором</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>, </span><span>обрабатываемых</span><span> </span><span>с</span><span> </span><span>помощью</span><span> </span><span>данного</span><span> </span><span>сайта</span><span>.</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>Cайт</span><span> – </span><span>Интернет</span><span>-</span><span>сайт</span><span> </span><a href="https://podpishi.org" style="text-decoration:none"><span style="text-decoration:underline; color:#0563c1">https</span></a><a href="https://podpishi.org" style="text-decoration:none"><span style="text-decoration:underline; color:#0563c1">://</span></a><a href="https://podpishi.org" style="text-decoration:none"><span style="text-decoration:underline; color:#0563c1">podpishi</span></a><a href="https://podpishi.org" style="text-decoration:none"><span style="text-decoration:underline; color:#0563c1">.</span></a><a href="https://podpishi.org" style="text-decoration:none"><span style="text-decoration:underline; color:#0563c1">org</span></a><span>, </span><span>через</span><span> </span><span>который</span><span> </span><span>осуществляется</span><span> </span><span>обработка</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>на</span><span> </span><span>основании</span><span> </span><span>настоящей</span><span> </span><span>Политики</span><span>.</span><a name="id.1fob9te"></a></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>Обращение</span><span> – </span><span>документ</span><span>, </span><span>формируемый</span><span> </span><span>в</span><span> </span><span>электронной</span><span> </span><span>форме</span><span> </span><span>на</span><span> </span><span>основе</span><span> </span><span>формуляра</span><span>, </span><span>размещаемого</span><span> </span><span>на</span><span> </span><span>Сайте</span><span>, </span><span>с</span><span> </span><span>использованием</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Заявителя</span><span>, </span><span>включая</span><span> </span><span>графический</span><span> </span><span>образ</span><span> </span><span>подписи</span><span> </span><span>Заявителя</span><span>.</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>Заявитель</span><span> – </span><span>гражданин</span><span> </span><span>России</span><span>, </span><span>заполнивший</span><span> </span><span>все</span><span> </span><span>обязательные</span><span> </span><span>поля</span><span> </span><span>формуляра</span><span> </span><span>Обращения</span><span> </span><span>на</span><span> </span><span>Сайте</span><span>, </span><span>поставивший</span><span> </span><span>отметку</span><span> </span><span>у</span><span> </span><span>надписи</span><span> «</span><span>Я</span><span> </span><span>поручаю</span><span> [</span><span>ФИО</span><span> </span><span>Поверенного</span><span>] </span><span>подать</span><span> </span><span>настоящее</span><span> </span><span>обращение</span><span> </span><span>Адресату</span><span> </span><span>на</span><span> </span><span>основании</span><span> </span><span>публичной</span><span> </span><span>оферты</span><span>» </span><span>и</span><span> </span><span>нажавший</span><span> </span><span>кнопку</span><span> «</span><span>Отправить</span><span>».</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>Адресат</span><span> – </span><span>орган</span><span> </span><span>государственной</span><span> </span><span>власти</span><span>, </span><span>орган</span><span> </span><span>местного</span><span> </span><span>самоуправления</span><span> </span><span>либо</span><span> </span><span>должностное</span><span> </span><span>лицо</span><span>, </span><span>которому</span><span> </span><span>адресовано</span><span> </span><span>Обращение</span><span>.</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>Поверенный</span><span> – </span><span>физическое</span><span> </span><span>лицо</span><span>, </span><span>которому</span><span> </span><span>Заявитель</span><span> </span><span>поручает</span><span> (</span><span>совместно</span><span> </span><span>с</span><span> </span><span>Оператором</span><span>) </span><span>сформировать</span><span> </span><span>Обращение</span><span>, </span><span>распечатать</span><span> </span><span>и</span><span> </span><span>передать</span><span> </span><span>его</span><span> </span><span>Адресату</span><span> </span><span>на</span><span> </span><span>основании</span><span> </span><span>Договора</span><span>, </span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>Договор</span><span> – </span><span>договор</span><span> </span><span>поручения</span><span>, </span><span>заключаемый</span><span> </span><span>между</span><span> </span><span>Заявителем</span><span> (</span><span>в</span><span> </span><span>качестве</span><span> </span><span>доверителя</span><span>), </span><span>с</span><span> </span><span>одной</span><span> </span><span>стороны</span><span>, </span><span>и</span><span> </span><span>Оператора</span><span> </span><span>и</span><span> </span><span>Поверенного</span><span> (</span><span>совместно</span><span> </span><span>именуемых</span><span> </span><span>в</span><span> </span><span>договоре</span><span> </span><span>Соповеренными</span><span>), </span><span>с</span><span> </span><span>другой</span><span> </span><span>стороны</span><span>, </span><span>путем</span><span> </span><span>принятия</span><span> </span><span>Заявителем</span><span> </span><span>публичной</span><span> </span><span>оферты</span><span>, </span><span>размещенной</span><span> </span><span>на</span><span> </span><span>Сайте</span><span>.</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>Персональные</span><span> </span><span>данные</span><span> </span><span>Заявителя</span><span> – </span><span>информация</span><span>, </span><span>необходимая</span><span> </span><span>для</span><span> </span><span>исполнения</span><span> </span><span>Договора</span><span> </span><span>и</span><span>, </span><span>в</span><span> </span><span>частности</span><span>, </span><span>для</span><span> </span><span>подачи</span><span> </span><span>Обращения</span><span> </span><span>Заявителя</span><span> </span><span>в</span><span> </span><span>соответствии</span><span> </span><span>с</span><span> </span><span>Федеральным</span><span> </span><span>законом</span><span> </span><span>от</span><span> 2 </span><span>мая</span><span> 2006 </span><span>г</span><span>. № 59-</span><span>ФЗ</span><span> «</span><span>О</span><span> </span><span>порядке</span><span> </span><span>рассмотрения</span><span> </span><span>обращений</span><span> </span><span>граждан</span><span> </span><span>Российской</span><span> </span><span>Федерации</span><span>», </span><span>включающая</span></li>
                    </ol>
                </li>
            </ol>
        </li>
    </ol>
    <p style="margin-top:0pt; margin-left:56.7pt; margin-bottom:0pt; text-align:justify; font-size:11pt"><span style="font-family:'Noto Sans Symbols'; font-size:10pt">●</span><span style="font:7pt 'Times New Roman'">&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;&#xa0; </span><span style="font-family:Calibri">фамилия</span><span style="font-family:Calibri">, </span><span style="font-family:Calibri">имя</span><span style="font-family:Calibri">, </span><span style="font-family:Calibri">отчество</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">Заявителя</span><span style="font-family:Calibri">;</span></p>
    <p style="margin-top:0pt; margin-left:56.7pt; margin-bottom:0pt; text-align:justify; font-size:11pt"><span style="font-family:'Noto Sans Symbols'; font-size:10pt">●</span><span style="font:7pt 'Times New Roman'">&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;&#xa0; </span><span style="font-family:Calibri">адрес</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">регистрации</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">Заявителя</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">по</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">месту</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">жительства</span><span style="font-family:Calibri"> (</span><span style="font-family:Calibri">или</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">адрес</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">фактического</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">проживания</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">Заявителя</span><span style="font-family:Calibri">);</span></p>
    <p style="margin-top:0pt; margin-left:56.7pt; margin-bottom:0pt; text-align:justify; font-size:11pt"><span style="font-family:'Noto Sans Symbols'; font-size:10pt">●</span><span style="font:7pt 'Times New Roman'">&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;&#xa0; </span><span style="font-family:Calibri">адрес</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">электронной</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">почты</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">Заявителя</span><span style="font-family:Calibri">;</span></p>
    <p style="margin-top:0pt; margin-left:56.7pt; margin-bottom:0pt; text-align:justify; font-size:11pt"><span style="font-family:'Noto Sans Symbols'; font-size:10pt">●</span><span style="font:7pt 'Times New Roman'">&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;&#xa0; </span><span style="font-family:Calibri">телефон</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">Заявителя</span><span style="font-family:Calibri">.</span></p>
    <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:108%; font-size:11pt"><span style="font-family:Calibri">1.3.</span><span style="font:7pt 'Times New Roman'"> </span><span style="font-family:Calibri">Прочие</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">термины</span><span style="font-family:Calibri">, </span><span style="font-family:Calibri">используемые</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">в</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">настоящей</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">Политике</span><span style="font-family:Calibri">, </span><span style="font-family:Calibri">имеют</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">значение</span><span style="font-family:Calibri">, </span><span style="font-family:Calibri">определенное</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">в</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">Федеральных</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">законах</span><span style="font-family:Calibri"> «</span><span style="font-family:Calibri">О</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">персональных</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">данных</span><span style="font-family:Calibri">», «</span><span style="font-family:Calibri">Об</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">информации</span><span style="font-family:Calibri">, </span><span style="font-family:Calibri">информационных</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">технологиях</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">и</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">о</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">защите</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">информации</span><span style="font-family:Calibri">», «</span><span style="font-family:Calibri">О</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">порядке</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">рассмотрения</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">обращений</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">граждан</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">Российской</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">Федерации</span><span style="font-family:Calibri">».</span></p>
    <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:108%; font-size:11pt"><span style="font-family:Calibri">1.4.</span><span style="font:7pt 'Times New Roman'"> </span><span style="font-family:Calibri">Оператор</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">осуществляет</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">обработку</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">персональных</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">данных</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">Участников</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">с</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">соблюдением</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">принципов</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">и</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">правил</span><span style="font-family:Calibri">, </span><span style="font-family:Calibri">предусмотренных</span><span style="font-family:Calibri"> </span><a href="garantF1://12048567.0" style="text-decoration:none"><span style="font-family:Calibri; color:#000000">Федеральным</span></a><a href="garantF1://12048567.0" style="text-decoration:none"><span style="font-family:Calibri; color:#000000"> </span></a><a href="garantF1://12048567.0" style="text-decoration:none"><span style="font-family:Calibri; color:#000000">законом</span></a><span style="font-family:Calibri"> «</span><span style="font-family:Calibri">О</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">персональных</span><span style="font-family:Calibri"> </span><span style="font-family:Calibri">данных</span><span style="font-family:Calibri">».</span></p>
    <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-36pt; text-align:justify; line-height:108%; font-size:11pt"><span style="font-family:Calibri">&#xa0;</span></p>
    <ol start="2" type="1" style="margin:0pt; padding-left:0pt">
        <li style="margin-left:31.51pt; line-height:108%; padding-left:4.49pt; font-family:Calibri; font-size:11pt; font-weight:bold">
            <span>Цели</span><span>, </span><span>способы</span><span> </span><span>и</span><span> </span><span>условия</span><span> </span><span>обработки</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Участников</span>
            <ol type="1" class="awlist3" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                <li style="text-indent:-18pt; text-align:justify; font-weight:normal; list-style-position:inside"><span>Обработка</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Участников</span><span> </span><span>осуществляется</span><span> </span><span>в</span><span> </span><span>целях</span><span> </span><span>заключения</span><span> </span><span>и</span><span> </span><span>исполнения</span><span> </span><span>Оператором</span><span> </span><span>и</span><span> </span><span>Поверенным</span><span> </span><span>Договоров</span><span> </span><span>с</span><span> </span><span>Заявителями</span><span>.</span></li>
                <li style="text-indent:-18pt; text-align:justify; font-weight:normal; list-style-position:inside"><span>Персональные</span><span> </span><span>данные</span><span> </span><span>Участников</span><span> </span><span>обрабатываются</span><span> </span><span>следующими</span><span> </span><span>способами</span><span>: </span><span>сбор</span><span>, </span><span>запись</span><span>, </span><span>систематизация</span><span>, </span><span>накопление</span><span>, </span><span>хранение</span><span>, </span><span>использование</span><span>, </span><span>передача</span><span> (</span><span>предоставление</span><span>), </span><span>обезличивание</span><span>, </span><span>трансграничная</span><span> </span><span>передача</span><span> </span><span>на</span><span> </span><span>территории</span><span> </span><span>иностранных</span><span> </span><span>государств</span><span>, </span><span>обеспечивающих</span><span> </span><span>адекватную</span><span> </span><span>защиту</span><span> </span><span>прав</span><span> </span><span>субъектов</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>, </span><span>блокирование</span><span>, </span><span>удаление</span><span>, </span><span>уничтожение</span><span>, </span><span>совершаемые</span><span> </span><span>с</span><span> </span><span>использованием</span><span> </span><span>средств</span><span> </span><span>автоматизации</span><span> </span><span>и</span><span> </span><span>без</span><span> </span><span>использования</span><span> </span><span>таковых</span><span>.</span></li>
                <li style="text-indent:-18pt; text-align:justify; font-weight:normal; list-style-position:inside"><span>Оператор</span><span> </span><span>приступает</span><span> </span><span>к</span><span> </span><span>обработке</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Заявителя</span><span> </span><span>при</span><span> </span><span>условии</span><span> </span><span>заключения</span><span> </span><span>Заявителем</span><span> </span><span>Договора</span><span> </span><span>в</span><span> </span><span>порядке</span><span>, </span><span>предусмотренном</span><span> </span><span>в</span><span> </span><span>подпунктах</span><span> 1.2.4, 1.2.7 </span><span>настоящей</span><span> </span><span>Политики</span><span>.</span></li>
            </ol>
        </li>
    </ol>
    <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-36pt; text-align:justify; line-height:108%; font-size:11pt"><span style="font-family:Calibri">&#xa0;</span></p>
    <ol start="3" type="1" style="margin:0pt; padding-left:0pt">
        <li style="margin-left:31.51pt; text-align:justify; line-height:108%; padding-left:4.49pt; font-family:Calibri; font-size:11pt; font-weight:bold">
            <span>Права</span><span> </span><span>и</span><span> </span><span>обязанности</span><span> </span><span>Оператора</span><span> </span><span>при</span><span> </span><span>обработке</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Заявителей</span>
            <ol type="1" class="awlist4" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                <li style="text-indent:-18pt; font-weight:normal; list-style-position:inside">
                    <span>Оператор</span><span> </span><span>при</span><span> </span><span>обработке</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>вправе</span><span>:</span>
                    <ol type="1" class="awlist5" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>устанавливать</span><span> </span><span>правила</span><span> </span><span>обработки</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Заявителя</span><span> </span><span>и</span><span> </span><span>вносить</span><span> </span><span>в</span><span> </span><span>них</span><span> (</span><span>в</span><span> </span><span>том</span><span> </span><span>числе</span><span> </span><span>в</span><span> </span><span>настоящую</span><span> </span><span>Политику</span><span>) </span><span>изменения</span><span> </span><span>и</span><span> </span><span>дополнения</span><span>;</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>по</span><span> </span><span>своему</span><span> </span><span>усмотрению</span><span> </span><span>организовать</span><span> </span><span>осуществление</span><span> </span><span>права</span><span> </span><span>Заявителя</span><span> </span><span>на</span><span> </span><span>доступ</span><span> </span><span>к</span><span> </span><span>своим</span><span> </span><span>персональным</span><span> </span><span>данным</span><span> </span><span>с</span><span> </span><span>соблюдением</span><span> </span><span>положений</span><span> </span><span>Федерального</span><span> </span><span>закона</span><span> «</span><span>О</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>».</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>распространить</span><span> </span><span>на</span><span> </span><span>Сайте</span><span> </span><span>обезличенные</span><span> </span><span>данные</span><span> </span><span>об</span><span> </span><span>адресах</span><span> </span><span>регистрации</span><span> </span><span>по</span><span> </span><span>месту</span><span> </span><span>жительства</span><span> (</span><span>либо</span><span> </span><span>адресах</span><span> </span><span>фактического</span><span> </span><span>проживания</span><span>) </span><span>Заявителей</span><span> </span><span>в</span><span> </span><span>форме</span><span>, </span><span>нанесенные</span><span> </span><span>на</span><span> </span><span>географическую</span><span> </span><span>карту</span><span>.</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>осуществлять</span><span> </span><span>иные</span><span> </span><span>права</span><span>, </span><span>предусмотренные</span><span> </span><span>законодательством</span><span> </span><span>РФ</span><span>.</span></li>
                    </ol>
                </li>
                <li style="text-indent:-18pt; font-weight:normal; list-style-position:inside"><span>Оператор</span><span> </span><span>при</span><span> </span><span>обработке</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>соблюдает</span><span> </span><span>обязанности</span><span>, </span><span>предусмотренные</span><span> </span><span>законодательством</span><span> </span><span>РФ</span><span>.</span></li>
            </ol>
        </li>
    </ol>
    <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-36pt; text-align:justify; line-height:108%; font-size:11pt"><span style="font-family:Calibri">&#xa0;</span></p>
    <ol start="4" type="1" style="margin:0pt; padding-left:0pt">
        <li style="margin-left:31.51pt; text-align:justify; line-height:108%; padding-left:4.49pt; font-family:Calibri; font-size:11pt; font-weight:bold">
            <span>Права</span><span> </span><span>и</span><span> </span><span>обязанности</span><span> </span><span>Заявителей</span><span> </span><span>при</span><span> </span><span>обработке</span><span> </span><span>их</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>через</span><span> </span><span>Сайт</span>
            <ol type="1" class="awlist6" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                <li style="text-indent:-18pt; font-weight:normal; list-style-position:inside">
                    <span>Заявитель</span><span> </span><span>пользуется</span><span> </span><span>правами</span><span>, </span><span>предусмотренными</span><span> </span><span>законодательством</span><span> </span><span>РФ</span><span> </span><span>в</span><span> </span><span>области</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>, </span><span>в</span><span> </span><span>частности</span><span>, </span><span>правом</span><span>:</span>
                    <ol type="1" class="awlist7" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>получать</span><span> </span><span>сведения</span><span> </span><span>об</span><span> </span><span>обработке</span><span> </span><span>своих</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>;</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>отозвать</span><span> (</span><span>полностью</span><span> </span><span>или</span><span> </span><span>частично</span><span>) </span><span>согласие</span><span> </span><span>на</span><span> </span><span>обработку</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>;</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>требовать</span><span> </span><span>от</span><span> </span><span>Оператора</span><span> </span><span>уточнения</span><span> </span><span>своих</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>, </span><span>их</span><span> </span><span>блокирования</span><span> </span><span>или</span><span> </span><span>уничтожения</span><span> </span><span>в</span><span> </span><span>случае</span><span>, </span><span>если</span><span> </span><span>персональные</span><span> </span><span>данные</span><span> </span><span>являются</span><span> </span><span>неполными</span><span>, </span><span>устаревшими</span><span>, </span><span>неточными</span><span>.</span></li>
                    </ol>
                </li>
                <li style="text-indent:-18pt; font-weight:normal; list-style-position:inside"><span>В целях осуществления своих прав, предусмотренных законодательством РФ в области персональных данных, Заявитель направляет Оператору запросы и обращения по электронной почте на адрес <a href="mailto:theshtab@gmail.com">theshtab@gmail.com</a></span></li>
                <li style="text-indent:-18pt; font-weight:normal; list-style-position:inside">
                    <span>Заявитель</span><span> </span><span>обязан</span><span>:</span>
                    <ol type="1" class="awlist8" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>обеспечить</span><span> </span><span>достоверность</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>, </span><span>передаваемых</span><span> </span><span>Оператору</span><span>;</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>предоставлять</span><span> </span><span>Оператору</span><span> </span><span>только</span><span> </span><span>свои</span><span> </span><span>персональные</span><span> </span><span>данные</span><span>. </span><span>В</span><span> </span><span>случае</span><span>, </span><span>если</span><span> </span><span>Заявитель</span><span> </span><span>предоставляет</span><span> </span><span>Оператору</span><span> </span><span>персональные</span><span> </span><span>данные</span><span> </span><span>третьего</span><span> </span><span>лица</span><span>, </span><span>такой</span><span> </span><span>Заявитель</span><span> </span><span>должен</span><span> </span><span>получить</span><span> </span><span>предварительное</span><span> </span><span>письменное</span><span> </span><span>согласие</span><span> </span><span>от</span><span> </span><span>субъекта</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>. </span><span>Получение</span><span> </span><span>такого</span><span> </span><span>согласия</span><span> </span><span>является</span><span> </span><span>обязанностью</span><span> </span><span>Заявителя</span><span>.</span></li>
                    </ol>
                </li>
            </ol>
        </li>
    </ol>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:108%; font-size:11pt"><span style="font-family:Calibri">&#xa0;</span></p>
    <ol start="5" type="1" style="margin:0pt; padding-left:0pt">
        <li style="margin-left:31.51pt; text-align:justify; line-height:108%; padding-left:4.49pt; font-family:Calibri; font-size:11pt; font-weight:bold">
            <span>Передача</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Участника</span><span> </span>
            <ol type="1" class="awlist9" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                <li style="text-indent:-18pt; font-weight:normal; list-style-position:inside"><span>В</span><span> </span><span>целях</span><span>, </span><span>указанных</span><span> </span><span>в</span><span> </span><span>пункте</span><span> 2.1 </span><span>настоящей</span><span> </span><span>Политики</span><span>, </span><span>Оператор</span><span> </span><span>на</span><span> </span><span>основании</span><span> </span><span>Договора</span><span> </span><span>передает</span><span> </span><span>персональные</span><span> </span><span>данные</span><span> </span><span>Поверенному</span><span> </span><span>и</span><span>, </span><span>далее</span><span> (</span><span>совместно</span><span> </span><span>с</span><span> </span><span>Поверенным</span><span>) – </span><span>Адресату</span><span>.</span></li>
                <li style="text-indent:-18pt; font-weight:normal; list-style-position:inside"><span>В</span><span> </span><span>целях</span><span>, </span><span>указанных</span><span> </span><span>в</span><span> </span><span>пункте</span><span> 2.1 </span><span>настоящей</span><span> </span><span>Политики</span><span>, </span><span>Оператор</span><span> </span><span>вправе</span><span> </span><span>передавать</span><span> </span><span>персональные</span><span> </span><span>данные</span><span> </span><span>Заявителя</span><span> </span><span>физическим</span><span> </span><span>и</span><span> </span><span>юридическим</span><span> </span><span>лицам</span><span>, </span><span>осуществляющим</span><span> </span><span>рассылки</span><span> (</span><span>в</span><span> </span><span>том</span><span> </span><span>числе</span><span> </span><span>почтовые</span><span>, </span><span>электронные</span><span> </span><span>и</span><span> </span><span>SMS</span><span>-</span><span>оповещений</span><span>) </span><span>сообщений</span><span>, </span><span>и</span><span> </span><span>организациям</span><span> </span><span>связи</span><span>. </span><span>Оператор</span><span> </span><span>выбирает</span><span> </span><span>указанные</span><span> </span><span>организации</span><span> </span><span>и</span><span> </span><span>лиц</span><span> </span><span>по</span><span> </span><span>своему</span><span> </span><span>усмотрению</span><span> </span><span>без</span><span> </span><span>дополнительного</span><span> </span><span>согласия</span><span> </span><span>Участника</span><span>.</span></li>
                <li style="text-indent:-18pt; font-weight:normal; list-style-position:inside"><span>Оператор</span><span> </span><span>вправе</span><span> </span><span>осуществлять</span><span> </span><span>передачу</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> (</span><span>в</span><span> </span><span>том</span><span> </span><span>числе</span><span> </span><span>трансграничную</span><span> </span><span>передачу</span><span> </span><span>на</span><span> </span><span>территории</span><span> </span><span>иностранных</span><span> </span><span>государств</span><span>, </span><span>обеспечивающих</span><span> </span><span>адекватную</span><span> </span><span>защиту</span><span> </span><span>прав</span><span> </span><span>субъектов</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>) </span><span>в</span><span> </span><span>целях</span><span> </span><span>их</span><span> </span><span>хранения</span><span> </span><span>хостинг</span><span>-</span><span>провайдерам</span><span>, </span><span>в</span><span> </span><span>том</span><span> </span><span>числе</span><span> </span><span>ООО</span><span> «</span><span>Бегет</span><span>» (</span><span>https</span><span>://</span><span>beget</span><span>.</span><span>com</span><span>/), </span><span>OVH</span><span> </span><span>Hosting Ltd</span><span> (</span><span>https</span><span>://</span><span>www</span><span>.</span><span>ovh</span><span>.</span><span>com</span><span>/). </span></li>
            </ol>
        </li>
    </ol>
    <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-36pt; text-align:justify; line-height:108%; font-size:11pt"><span style="font-family:Calibri">&#xa0;</span></p>
    <ol start="6" type="1" style="margin:0pt; padding-left:0pt">
        <li style="margin-left:31.51pt; text-align:justify; line-height:108%; padding-left:4.49pt; font-family:Calibri; font-size:11pt; font-weight:bold">
            <span>Защита</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Заявителя</span>
            <ol type="1" class="awlist10" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                <li style="text-indent:-18pt; font-weight:normal; list-style-position:inside"><span>Защита</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Заявителя</span><span> </span><span>от</span><span> </span><span>неправомерного</span><span> </span><span>их</span><span> </span><span>использования</span><span> </span><span>или</span><span> </span><span>утраты</span><span> </span><span>обеспечивается</span><span> </span><span>Оператором</span><span> </span><span>за</span><span> </span><span>счет</span><span> </span><span>собственных</span><span> </span><span>средств</span><span> </span><span>в</span><span> </span><span>порядке</span><span>, </span><span>установленном</span><span> </span><span>законодательством</span><span> </span><span>РФ</span><span>.</span></li>
                <li style="text-indent:-18pt; font-weight:normal; list-style-position:inside">
                    <span>В</span><span> </span><span>целях</span><span> </span><span>защиты</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Заявителей</span><span> </span><span>Оператор</span><span>, </span><span>в</span><span> </span><span>частности</span><span>: </span>
                    <ol type="1" class="awlist11" style="margin-right:0pt; margin-left:0pt; padding-left:0pt">
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>определяет</span><span> </span><span>угрозы</span><span> </span><span>безопасности</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>при</span><span> </span><span>их</span><span> </span><span>обработке</span><span> </span><span>в</span><span> </span><span>информационных</span><span> </span><span>системах</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>, </span><span>оценивает</span><span> </span><span>эффективность</span><span> </span><span>принимаемых</span><span> </span><span>мер</span><span> </span><span>по</span><span> </span><span>обеспечению</span><span> </span><span>безопасности</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>в</span><span> </span><span>информационных</span><span> </span><span>системах</span><span>;</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>обязывает</span><span> </span><span>Поверенных</span><span> </span><span>сохранять</span><span> </span><span>конфиденциальность</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Заявителей</span><span>, </span><span>за</span><span> </span><span>исключением</span><span> </span><span>случаев</span><span>, </span><span>когда</span><span> </span><span>их</span><span> </span><span>разглашение</span><span> </span><span>предусмотрено</span><span> </span><span>Договорами</span><span>;</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><a name="h.3znysh7"></a><span>ограничивает</span><span> </span><span>паролями</span><span> </span><span>доступ</span><span> </span><span>к</span><span> </span><span>информационной</span><span> </span><span>системе</span><span> </span><span>и</span><span> </span><span>к</span><span> </span><span>персональным</span><span> </span><span>компьютерам</span><span>, </span><span>в</span><span> </span><span>которых</span><span> </span><span>обрабатываются</span><span> </span><span>персональные</span><span> </span><span>данные</span><span> </span><span>Участников</span><span>;</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>доводит</span><span> </span><span>до</span><span> </span><span>Поверенных</span><span> </span><span>информацию</span><span> </span><span>по</span><span> </span><span>предупреждению</span><span> </span><span>утраты</span><span> </span><span>персональных</span><span> </span><span>данных</span><span> </span><span>Участников</span><span> </span><span>и</span><span> </span><span>несанкционированного</span><span> </span><span>доступа</span><span> </span><span>к</span><span> </span><span>ним</span><span>;</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>обеспечивает</span><span> </span><span>регистрацию</span><span> </span><span>всех</span><span> </span><span>действий</span><span>, </span><span>совершаемых</span><span> </span><span>с</span><span> </span><span>персональными</span><span> </span><span>данными</span><span> </span><span>Заявителей</span><span> </span><span>в</span><span> </span><span>информационной</span><span> </span><span>системе</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>.</span></li>
                        <li style="margin-left:18pt; text-indent:-36pt; -aw-list-padding-sml:5.94pt"><span style="font:7pt 'Times New Roman'; -aw-list-padding-sml:5.94pt">&#xa0;&#xa0;&#xa0; </span><span>принимает</span><span> </span><span>другие</span><span> </span><span>меры</span><span> </span><span>обеспечения</span><span> </span><span>безопасности</span><span> </span><span>персональных</span><span> </span><span>данных</span><span>, </span><span>предусмотренные</span><span> </span><span>законодательством</span><span> </span><span>РФ</span><span>.</span></li>
                    </ol>
                </li>
            </ol>
        </li>
    </ol>
</div>
</body>
</html>
